language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.6
  - 7.0.10

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.7.3 WP_MULTISITE=0

matrix:
  include:
    - php: 7.0.10
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
